export interface ThemeTokens {
  '--color-accent': string
  '--color-accent-rgb': string
  '--color-accent-foreground': string
  '--color-accent-light': string
  '--color-accent-lighter': string
  '--color-accent-muted': string
  '--color-accent-subtle': string
  '--color-accent-glow': string
  '--color-bg': string
  '--color-surface': string
  '--color-surface-secondary': string
  '--color-surface-tertiary': string
  '--color-surface-hover': string
  '--color-surface-elevated': string
  '--color-surface-overlay': string
  '--color-text': string
  '--color-text-secondary': string
  '--color-text-tertiary': string
  '--color-text-quaternary': string
  '--color-border': string
  '--color-border-light': string
  '--color-border-hover': string
}

export interface ColorScheme {
  id: string
  name: string
  nameZh: string
  light: ThemeTokens
  dark: ThemeTokens
  /** Preview accent color for the scheme picker */
  previewColor: string
}

const terracotta: ColorScheme = {
  id: 'terracotta',
  name: 'Terracotta',
  nameZh: '陶土色',
  previewColor: '#8b4c3c',
  light: {
    '--color-accent': '#8b4c3c',
    '--color-accent-rgb': '139, 76, 60',
    '--color-accent-foreground': '#ffffff',
    '--color-accent-light': '#a66a5a',
    '--color-accent-lighter': '#c08d7a',
    '--color-accent-muted': 'rgba(139, 76, 60, 0.1)',
    '--color-accent-subtle': 'rgba(139, 76, 60, 0.05)',
    '--color-accent-glow': 'rgba(139, 76, 60, 0.18)',
    '--color-bg': '#fdfcfb',
    '--color-surface': '#ffffff',
    '--color-surface-secondary': '#f9f8f6',
    '--color-surface-tertiary': '#f1f0ed',
    '--color-surface-hover': '#f4f3f0',
    '--color-surface-elevated': '#ffffff',
    '--color-surface-overlay': 'rgba(0, 0, 0, 0.25)',
    '--color-text': '#1c1b1a',
    '--color-text-secondary': '#6b6965',
    '--color-text-tertiary': '#96948f',
    '--color-text-quaternary': '#c2c1bc',
    '--color-border': '#ebeae7',
    '--color-border-light': '#f1f0ed',
    '--color-border-hover': '#dfddd9',
  },
  dark: {
    '--color-accent': '#c49a8c',
    '--color-accent-rgb': '196, 154, 140',
    '--color-accent-foreground': '#11100f',
    '--color-accent-light': '#d4b5a8',
    '--color-accent-lighter': '#e0c9bf',
    '--color-accent-muted': 'rgba(196, 154, 140, 0.12)',
    '--color-accent-subtle': 'rgba(196, 154, 140, 0.06)',
    '--color-accent-glow': 'rgba(196, 154, 140, 0.2)',
    '--color-bg': '#11100f',
    '--color-surface': '#191817',
    '--color-surface-secondary': '#1f1e1c',
    '--color-surface-tertiary': '#272624',
    '--color-surface-hover': '#272624',
    '--color-surface-elevated': '#1f1e1c',
    '--color-surface-overlay': 'rgba(0, 0, 0, 0.4)',
    '--color-text': '#f2f1f0',
    '--color-text-secondary': '#a6a4a0',
    '--color-text-tertiary': '#73716d',
    '--color-text-quaternary': '#4d4b48',
    '--color-border': '#272624',
    '--color-border-light': '#201f1d',
    '--color-border-hover': '#363532',
  },
}

const kleinBlue: ColorScheme = {
  id: 'klein-blue',
  name: 'Klein Blue',
  nameZh: '克莱因蓝',
  previewColor: '#002fa7',
  light: {
    '--color-accent': '#002fa7',
    '--color-accent-rgb': '0, 47, 167',
    '--color-accent-foreground': '#ffffff',
    '--color-accent-light': '#1e4fc7',
    '--color-accent-lighter': '#4d7cff',
    '--color-accent-muted': 'rgba(0, 47, 167, 0.1)',
    '--color-accent-subtle': 'rgba(0, 47, 167, 0.05)',
    '--color-accent-glow': 'rgba(0, 47, 167, 0.18)',
    '--color-bg': '#f8f9fc',
    '--color-surface': '#ffffff',
    '--color-surface-secondary': '#f5f6fa',
    '--color-surface-tertiary': '#edf0f7',
    '--color-surface-hover': '#f0f3f8',
    '--color-surface-elevated': '#ffffff',
    '--color-surface-overlay': 'rgba(0, 0, 0, 0.25)',
    '--color-text': '#0f1729',
    '--color-text-secondary': '#4a5568',
    '--color-text-tertiary': '#8891a5',
    '--color-text-quaternary': '#bcc3d0',
    '--color-border': '#e4e8f0',
    '--color-border-light': '#eef1f6',
    '--color-border-hover': '#d0d6e3',
  },
  dark: {
    '--color-accent': '#4d7cff',
    '--color-accent-rgb': '77, 124, 255',
    '--color-accent-foreground': '#ffffff',
    '--color-accent-light': '#6d95ff',
    '--color-accent-lighter': '#8aadff',
    '--color-accent-muted': 'rgba(77, 124, 255, 0.12)',
    '--color-accent-subtle': 'rgba(77, 124, 255, 0.06)',
    '--color-accent-glow': 'rgba(77, 124, 255, 0.2)',
    '--color-bg': '#0a0b14',
    '--color-surface': '#11131e',
    '--color-surface-secondary': '#171a28',
    '--color-surface-tertiary': '#1e2235',
    '--color-surface-hover': '#1e2235',
    '--color-surface-elevated': '#171a28',
    '--color-surface-overlay': 'rgba(0, 0, 0, 0.45)',
    '--color-text': '#eef0f6',
    '--color-text-secondary': '#9da3b8',
    '--color-text-tertiary': '#6b7188',
    '--color-text-quaternary': '#454a5e',
    '--color-border': '#1e2235',
    '--color-border-light': '#181b2a',
    '--color-border-hover': '#2a3048',
  },
}

const forestGreen: ColorScheme = {
  id: 'forest-green',
  name: 'Forest Green',
  nameZh: '森林绿',
  previewColor: '#2d6a4f',
  light: {
    '--color-accent': '#2d6a4f',
    '--color-accent-rgb': '45, 106, 79',
    '--color-accent-foreground': '#ffffff',
    '--color-accent-light': '#40916c',
    '--color-accent-lighter': '#52b788',
    '--color-accent-muted': 'rgba(45, 106, 79, 0.1)',
    '--color-accent-subtle': 'rgba(45, 106, 79, 0.05)',
    '--color-accent-glow': 'rgba(45, 106, 79, 0.18)',
    '--color-bg': '#f9fbf9',
    '--color-surface': '#ffffff',
    '--color-surface-secondary': '#f5f8f5',
    '--color-surface-tertiary': '#edf4ee',
    '--color-surface-hover': '#f0f6f1',
    '--color-surface-elevated': '#ffffff',
    '--color-surface-overlay': 'rgba(0, 0, 0, 0.25)',
    '--color-text': '#1a1f1c',
    '--color-text-secondary': '#5a6b60',
    '--color-text-tertiary': '#88998e',
    '--color-text-quaternary': '#b8c4bb',
    '--color-border': '#e4ede6',
    '--color-border-light': '#eef4ef',
    '--color-border-hover': '#d0dbd3',
  },
  dark: {
    '--color-accent': '#52b788',
    '--color-accent-rgb': '82, 183, 136',
    '--color-accent-foreground': '#0a0f0c',
    '--color-accent-light': '#6ecba0',
    '--color-accent-lighter': '#8ad8b4',
    '--color-accent-muted': 'rgba(82, 183, 136, 0.12)',
    '--color-accent-subtle': 'rgba(82, 183, 136, 0.06)',
    '--color-accent-glow': 'rgba(82, 183, 136, 0.2)',
    '--color-bg': '#0c100e',
    '--color-surface': '#131916',
    '--color-surface-secondary': '#1a221d',
    '--color-surface-tertiary': '#212c26',
    '--color-surface-hover': '#212c26',
    '--color-surface-elevated': '#1a221d',
    '--color-surface-overlay': 'rgba(0, 0, 0, 0.45)',
    '--color-text': '#edf5f0',
    '--color-text-secondary': '#a3b8ab',
    '--color-text-tertiary': '#708a78',
    '--color-text-quaternary': '#465c4e',
    '--color-border': '#212c26',
    '--color-border-light': '#1a231d',
    '--color-border-hover': '#2d3d34',
  },
}

const sakura: ColorScheme = {
  id: 'sakura',
  name: 'Sakura',
  nameZh: '樱花粉',
  previewColor: '#d4697a',
  light: {
    '--color-accent': '#d4697a',
    '--color-accent-rgb': '212, 105, 122',
    '--color-accent-foreground': '#ffffff',
    '--color-accent-light': '#de8d99',
    '--color-accent-lighter': '#e8b0b8',
    '--color-accent-muted': 'rgba(212, 105, 122, 0.1)',
    '--color-accent-subtle': 'rgba(212, 105, 122, 0.05)',
    '--color-accent-glow': 'rgba(212, 105, 122, 0.18)',
    '--color-bg': '#fdfafb',
    '--color-surface': '#ffffff',
    '--color-surface-secondary': '#faf6f7',
    '--color-surface-tertiary': '#f5edef',
    '--color-surface-hover': '#f7f0f2',
    '--color-surface-elevated': '#ffffff',
    '--color-surface-overlay': 'rgba(0, 0, 0, 0.25)',
    '--color-text': '#1f181a',
    '--color-text-secondary': '#6b565b',
    '--color-text-tertiary': '#9b8589',
    '--color-text-quaternary': '#c5b5b8',
    '--color-border': '#efe4e6',
    '--color-border-light': '#f5edef',
    '--color-border-hover': '#e2d1d4',
  },
  dark: {
    '--color-accent': '#e8a0aa',
    '--color-accent-rgb': '232, 160, 170',
    '--color-accent-foreground': '#1a1013',
    '--color-accent-light': '#eebcc3',
    '--color-accent-lighter': '#f4d0d5',
    '--color-accent-muted': 'rgba(232, 160, 170, 0.12)',
    '--color-accent-subtle': 'rgba(232, 160, 170, 0.06)',
    '--color-accent-glow': 'rgba(232, 160, 170, 0.2)',
    '--color-bg': '#131011',
    '--color-surface': '#1c1719',
    '--color-surface-secondary': '#241e20',
    '--color-surface-tertiary': '#2d2527',
    '--color-surface-hover': '#2d2527',
    '--color-surface-elevated': '#241e20',
    '--color-surface-overlay': 'rgba(0, 0, 0, 0.45)',
    '--color-text': '#f5edef',
    '--color-text-secondary': '#b8a1a5',
    '--color-text-tertiary': '#8a7277',
    '--color-text-quaternary': '#5c4c4f',
    '--color-border': '#2d2527',
    '--color-border-light': '#241e20',
    '--color-border-hover': '#3d3235',
  },
}

const midnightPurple: ColorScheme = {
  id: 'midnight-purple',
  name: 'Midnight Purple',
  nameZh: '暗夜紫',
  previewColor: '#6b3fa0',
  light: {
    '--color-accent': '#6b3fa0',
    '--color-accent-rgb': '107, 63, 160',
    '--color-accent-foreground': '#ffffff',
    '--color-accent-light': '#8454b8',
    '--color-accent-lighter': '#a07bcc',
    '--color-accent-muted': 'rgba(107, 63, 160, 0.1)',
    '--color-accent-subtle': 'rgba(107, 63, 160, 0.05)',
    '--color-accent-glow': 'rgba(107, 63, 160, 0.18)',
    '--color-bg': '#fbfafd',
    '--color-surface': '#ffffff',
    '--color-surface-secondary': '#f8f6fb',
    '--color-surface-tertiary': '#f1ecf7',
    '--color-surface-hover': '#f4f0f8',
    '--color-surface-elevated': '#ffffff',
    '--color-surface-overlay': 'rgba(0, 0, 0, 0.25)',
    '--color-text': '#1a1720',
    '--color-text-secondary': '#5e566b',
    '--color-text-tertiary': '#8e85a0',
    '--color-text-quaternary': '#c0b8cc',
    '--color-border': '#ebe4f2',
    '--color-border-light': '#f2edf7',
    '--color-border-hover': '#d8cde6',
  },
  dark: {
    '--color-accent': '#a07bcc',
    '--color-accent-rgb': '160, 123, 204',
    '--color-accent-foreground': '#100c18',
    '--color-accent-light': '#b594d8',
    '--color-accent-lighter': '#c9ade3',
    '--color-accent-muted': 'rgba(160, 123, 204, 0.12)',
    '--color-accent-subtle': 'rgba(160, 123, 204, 0.06)',
    '--color-accent-glow': 'rgba(160, 123, 204, 0.2)',
    '--color-bg': '#0f0c15',
    '--color-surface': '#17131f',
    '--color-surface-secondary': '#1e1929',
    '--color-surface-tertiary': '#262033',
    '--color-surface-hover': '#262033',
    '--color-surface-elevated': '#1e1929',
    '--color-surface-overlay': 'rgba(0, 0, 0, 0.45)',
    '--color-text': '#f1ecf7',
    '--color-text-secondary': '#b0a0c4',
    '--color-text-tertiary': '#7e7099',
    '--color-text-quaternary': '#504566',
    '--color-border': '#262033',
    '--color-border-light': '#1e1929',
    '--color-border-hover': '#352d45',
  },
}

const amberGold: ColorScheme = {
  id: 'amber-gold',
  name: 'Amber Gold',
  nameZh: '琥珀金',
  previewColor: '#b87a2b',
  light: {
    '--color-accent': '#b87a2b',
    '--color-accent-rgb': '184, 122, 43',
    '--color-accent-foreground': '#ffffff',
    '--color-accent-light': '#ca9446',
    '--color-accent-lighter': '#dbaf6b',
    '--color-accent-muted': 'rgba(184, 122, 43, 0.1)',
    '--color-accent-subtle': 'rgba(184, 122, 43, 0.05)',
    '--color-accent-glow': 'rgba(184, 122, 43, 0.18)',
    '--color-bg': '#fdfaf5',
    '--color-surface': '#ffffff',
    '--color-surface-secondary': '#faf6ed',
    '--color-surface-tertiary': '#f5edd9',
    '--color-surface-hover': '#f7f0e0',
    '--color-surface-elevated': '#ffffff',
    '--color-surface-overlay': 'rgba(0, 0, 0, 0.25)',
    '--color-text': '#1f1a10',
    '--color-text-secondary': '#6b5f4a',
    '--color-text-tertiary': '#9b8b70',
    '--color-text-quaternary': '#c5baa8',
    '--color-border': '#ede2c8',
    '--color-border-light': '#f5edd9',
    '--color-border-hover': '#e0d0ad',
  },
  dark: {
    '--color-accent': '#dbaf6b',
    '--color-accent-rgb': '219, 175, 107',
    '--color-accent-foreground': '#1a1208',
    '--color-accent-light': '#e2c085',
    '--color-accent-lighter': '#ebd0a3',
    '--color-accent-muted': 'rgba(219, 175, 107, 0.12)',
    '--color-accent-subtle': 'rgba(219, 175, 107, 0.06)',
    '--color-accent-glow': 'rgba(219, 175, 107, 0.2)',
    '--color-bg': '#100e0a',
    '--color-surface': '#191612',
    '--color-surface-secondary': '#221d17',
    '--color-surface-tertiary': '#2c241c',
    '--color-surface-hover': '#2c241c',
    '--color-surface-elevated': '#221d17',
    '--color-surface-overlay': 'rgba(0, 0, 0, 0.45)',
    '--color-text': '#f7f0e0',
    '--color-text-secondary': '#b8a88a',
    '--color-text-tertiary': '#8a7a5c',
    '--color-text-quaternary': '#5c503d',
    '--color-border': '#2c241c',
    '--color-border-light': '#221d17',
    '--color-border-hover': '#3d3328',
  },
}

const slateGray: ColorScheme = {
  id: 'slate-gray',
  name: 'Slate Gray',
  nameZh: '岩板灰',
  previewColor: '#5b7a8c',
  light: {
    '--color-accent': '#5b7a8c',
    '--color-accent-rgb': '91, 122, 140',
    '--color-accent-foreground': '#ffffff',
    '--color-accent-light': '#7392a3',
    '--color-accent-lighter': '#93b0be',
    '--color-accent-muted': 'rgba(91, 122, 140, 0.1)',
    '--color-accent-subtle': 'rgba(91, 122, 140, 0.05)',
    '--color-accent-glow': 'rgba(91, 122, 140, 0.18)',
    '--color-bg': '#f8f9fa',
    '--color-surface': '#ffffff',
    '--color-surface-secondary': '#f5f6f8',
    '--color-surface-tertiary': '#eef0f3',
    '--color-surface-hover': '#f0f2f5',
    '--color-surface-elevated': '#ffffff',
    '--color-surface-overlay': 'rgba(0, 0, 0, 0.25)',
    '--color-text': '#171b1e',
    '--color-text-secondary': '#556068',
    '--color-text-tertiary': '#828d95',
    '--color-text-quaternary': '#b4bdc4',
    '--color-border': '#e4e8ec',
    '--color-border-light': '#eef1f4',
    '--color-border-hover': '#d0d6dc',
  },
  dark: {
    '--color-accent': '#93b0be',
    '--color-accent-rgb': '147, 176, 190',
    '--color-accent-foreground': '#0c1114',
    '--color-accent-light': '#a8c2ce',
    '--color-accent-lighter': '#bdd3dc',
    '--color-accent-muted': 'rgba(147, 176, 190, 0.12)',
    '--color-accent-subtle': 'rgba(147, 176, 190, 0.06)',
    '--color-accent-glow': 'rgba(147, 176, 190, 0.2)',
    '--color-bg': '#0c0f12',
    '--color-surface': '#13171a',
    '--color-surface-secondary': '#191e22',
    '--color-surface-tertiary': '#20262b',
    '--color-surface-hover': '#20262b',
    '--color-surface-elevated': '#191e22',
    '--color-surface-overlay': 'rgba(0, 0, 0, 0.45)',
    '--color-text': '#eef2f5',
    '--color-text-secondary': '#a3aeb6',
    '--color-text-tertiary': '#73808a',
    '--color-text-quaternary': '#4a555d',
    '--color-border': '#20262b',
    '--color-border-light': '#191e22',
    '--color-border-hover': '#2c343a',
  },
}

const oceanTeal: ColorScheme = {
  id: 'ocean-teal',
  name: 'Ocean Teal',
  nameZh: '海洋青',
  previewColor: '#0d7b7b',
  light: {
    '--color-accent': '#0d7b7b',
    '--color-accent-rgb': '13, 123, 123',
    '--color-accent-foreground': '#ffffff',
    '--color-accent-light': '#1a9696',
    '--color-accent-lighter': '#2db5b5',
    '--color-accent-muted': 'rgba(13, 123, 123, 0.1)',
    '--color-accent-subtle': 'rgba(13, 123, 123, 0.05)',
    '--color-accent-glow': 'rgba(13, 123, 123, 0.18)',
    '--color-bg': '#f7fafa',
    '--color-surface': '#ffffff',
    '--color-surface-secondary': '#f4f8f8',
    '--color-surface-tertiary': '#eaf3f3',
    '--color-surface-hover': '#edf5f5',
    '--color-surface-elevated': '#ffffff',
    '--color-surface-overlay': 'rgba(0, 0, 0, 0.25)',
    '--color-text': '#141f1f',
    '--color-text-secondary': '#4d6161',
    '--color-text-tertiary': '#788f8f',
    '--color-text-quaternary': '#aec0c0',
    '--color-border': '#dce9e9',
    '--color-border-light': '#e8f1f1',
    '--color-border-hover': '#c6d8d8',
  },
  dark: {
    '--color-accent': '#2db5b5',
    '--color-accent-rgb': '45, 181, 181',
    '--color-accent-foreground': '#081414',
    '--color-accent-light': '#4dc4c4',
    '--color-accent-lighter': '#6dd3d3',
    '--color-accent-muted': 'rgba(45, 181, 181, 0.12)',
    '--color-accent-subtle': 'rgba(45, 181, 181, 0.06)',
    '--color-accent-glow': 'rgba(45, 181, 181, 0.2)',
    '--color-bg': '#0a1212',
    '--color-surface': '#101919',
    '--color-surface-secondary': '#162121',
    '--color-surface-tertiary': '#1d2b2b',
    '--color-surface-hover': '#1d2b2b',
    '--color-surface-elevated': '#162121',
    '--color-surface-overlay': 'rgba(0, 0, 0, 0.45)',
    '--color-text': '#eaf3f3',
    '--color-text-secondary': '#a0bbbb',
    '--color-text-tertiary': '#6e9191',
    '--color-text-quaternary': '#446060',
    '--color-border': '#1d2b2b',
    '--color-border-light': '#162121',
    '--color-border-hover': '#283b3b',
  },
}

const crimson: ColorScheme = {
  id: 'crimson',
  name: 'Crimson',
  nameZh: '赤霞红',
  previewColor: '#c1292e',
  light: {
    '--color-accent': '#c1292e',
    '--color-accent-rgb': '193, 41, 46',
    '--color-accent-foreground': '#ffffff',
    '--color-accent-light': '#d44549',
    '--color-accent-lighter': '#e06e72',
    '--color-accent-muted': 'rgba(193, 41, 46, 0.1)',
    '--color-accent-subtle': 'rgba(193, 41, 46, 0.05)',
    '--color-accent-glow': 'rgba(193, 41, 46, 0.18)',
    '--color-bg': '#fdfafb',
    '--color-surface': '#ffffff',
    '--color-surface-secondary': '#faf6f7',
    '--color-surface-tertiary': '#f5edef',
    '--color-surface-hover': '#f7eff1',
    '--color-surface-elevated': '#ffffff',
    '--color-surface-overlay': 'rgba(0, 0, 0, 0.25)',
    '--color-text': '#1f1516',
    '--color-text-secondary': '#6b4e50',
    '--color-text-tertiary': '#9b787a',
    '--color-text-quaternary': '#c5abad',
    '--color-border': '#efe0e1',
    '--color-border-light': '#f5ebec',
    '--color-border-hover': '#e2cbcd',
  },
  dark: {
    '--color-accent': '#e06e72',
    '--color-accent-rgb': '224, 110, 114',
    '--color-accent-foreground': '#1a0c0d',
    '--color-accent-light': '#e68a8d',
    '--color-accent-lighter': '#eda6a8',
    '--color-accent-muted': 'rgba(224, 110, 114, 0.12)',
    '--color-accent-subtle': 'rgba(224, 110, 114, 0.06)',
    '--color-accent-glow': 'rgba(224, 110, 114, 0.2)',
    '--color-bg': '#120e0f',
    '--color-surface': '#1a1415',
    '--color-surface-secondary': '#221a1b',
    '--color-surface-tertiary': '#2d2123',
    '--color-surface-hover': '#2d2123',
    '--color-surface-elevated': '#221a1b',
    '--color-surface-overlay': 'rgba(0, 0, 0, 0.45)',
    '--color-text': '#f5edee',
    '--color-text-secondary': '#b89d9f',
    '--color-text-tertiary': '#8a6f71',
    '--color-text-quaternary': '#5c494b',
    '--color-border': '#2d2123',
    '--color-border-light': '#221a1b',
    '--color-border-hover': '#3d2e30',
  },
}

export const COLOR_SCHEMES: ColorScheme[] = [
  terracotta,
  kleinBlue,
  forestGreen,
  sakura,
  midnightPurple,
  amberGold,
  slateGray,
  oceanTeal,
  crimson,
]

export const DEFAULT_COLOR_SCHEME = 'terracotta'

export function getColorScheme(id: string): ColorScheme | undefined {
  return COLOR_SCHEMES.find((s) => s.id === id)
}

export function getActiveTokens(schemeId: string, mode: 'light' | 'dark'): ThemeTokens {
  const scheme = getColorScheme(schemeId) || terracotta
  return mode === 'dark' ? scheme.dark : scheme.light
}
